name: Build binary files

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [cod2_1_0, cod2_1_2, cod2_1_3]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y build-essential g++-multilib libmysqlclient-dev:i386 libsqlite3-dev:i386

      - name: Make build script executable
        run: chmod +x ./doit.sh

      - name: Clean previous build
        run: ./doit.sh clean || true

      - name: Build target ${{ matrix.target }}
        run: ./doit.sh ${{ matrix.target }}

      - name: Verify build output for ${{ matrix.target }}
        run: |
          if [ ! -f bin/lib${{ matrix.target }}.so ]; then
            echo "Build failed: bin/lib${{ matrix.target }}.so not found"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib${{ matrix.target }}
          path: bin/lib${{ matrix.target }}.so
