name: Build binary files

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:buster-20210311-slim
    strategy:
      matrix:
        target: [cod2_1_0, cod2_1_2, cod2_1_3]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies in container
        run: |
          dpkg --add-architecture i386
          apt-get update
          apt-get install -y --no-install-recommends libstdc++5:i386=1:3.3.6-30
          apt-get install -y --no-install-recommends g++-multilib=4:8.3.0-1
          apt-get install -y --no-install-recommends default-libmysqlclient-dev:i386=1.0.5
          apt-get install -y --no-install-recommends libsqlite3-0:i386=3.27.2-3+deb10u1 libsqlite3-dev:i386=3.27.2-3+deb10u1

      - name: Make build script executable
        run: chmod +x ./doit.sh

      - name: Clean previous build
        run: ./doit.sh clean || true

      - name: Build target ${{ matrix.target }}
        run: ./doit.sh ${{ matrix.target }}

      - name: Verify build output for ${{ matrix.target }}
        run: |
          if [ ! -f bin/lib${{ matrix.target }}.so ]; then
            echo "Build failed: bin/lib${{ matrix.target }}.so not found"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib${{ matrix.target }}
          path: bin/lib${{ matrix.target }}.so